<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NRMI-55" name="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest" tests="20" failures="0" timestamp="18 Sep 2020 06:52:41 GMT" time="12.363" errors="7">
  <testcase name="createOrUpdateAgentTest" time="0.791" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.716" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.517" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.802" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.456" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.575" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.429" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.651" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.526" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.419" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.475" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.650" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.590" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.633" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.396" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.950" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.711" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
  <testcase name="createOrUpdateAgentTest" time="0.766" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.660" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest"/>
  <testcase name="createOrUpdateAgentTest" time="0.650" classname="in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest">
    <error type="java.lang.AssertionError" message="TEST FAILED!!! Assertion error..!">
      <![CDATA[java.lang.AssertionError: TEST FAILED!!! Assertion error..!
	at org.testng.Assert.fail(Assert.java:94)
	at in.novopay.cbs.utils.ApiUtils.assertAPIResponseStatus(ApiUtils.java:306)
	at in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest.createOrUpdateAgentTest(CreateOrUpdateAgentTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createOrUpdateAgentTest -->
</testsuite> <!-- in.novopay.cbs.apis.createorupdateagent.CreateOrUpdateAgentTest -->
